#!/bin/sh

# Copyright © 2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage()
{
    printf 'Usage: %s TIME COMMAND [ARGS...]\n' "${0##*/}" >&2
    exit 1
}

[ $# -ge 2 ] || usage
time="$1"
shift
[ "${time#[[:digit:]]}" != "$time" ] || usage
sleep "$time"
exec "$@"

# vim:ts=4 sts=4 sw=4 et
